### PR TITLE
fix logger error for trpo_mpi

### PR DESCRIPTION
**Pull request by 20chase**
Can't run logger.configure() if rank != 0

### CODE REVIEW

**Comment by 20chase** [comment]
Hi @joschu 

trpo_mpi cannot run with mpi4py because logger.configure() assert rank=0.
so I modify the run_mujoco.py according to ppo1 to make it work. : )

**Comment by joschu** [comment]
why change the section with argparse?

**Comment by 20chase** [comment]
sorry, I have fixed it.

**Comment by joschu** [comment]
Cool, merged

**Pull request merged**
