### PR TITLE
Fix perturb_vars bug. Fix reshape () in ddpg. Enhance numerical stability when sample.  

### PR DESCRIPTION
**Pull request by cxxgtxy**

### CODE REVIEW

**Comment by cxxgtxy** [comment]
Anyone check it ?

**Comment by lukashermann** [comment]
I checked it, didn't solve the nan problem in #127

**Comment by cxxgtxy** [comment]
You are right. It doesn't solve the NAN  for acktr. But help to solve NAN in other method such as PPO. I will check acktr carefully.

**Comment by eshung** [comment]
I think your original fix perturb_vars bug pull request fixes #157

**Comment by matthiasplappert** [comment]
Addressed by https://github.com/openai/baselines/commit/49c1a8ec26f738cef6a4406550bf219299164f25

**Pull request closed without merging**
