### PR TITLE
tf2: Updated setup.py dependencies.

### PR DESCRIPTION
**Pull request by pisiiki**
Setup will now install latest tf2 and latest compatible gym.

### CODE REVIEW

**Comment by pisiiki** [comment]
About the changes: I was unable to install the baselines tf2 pip package (windows10, python 3.7.4). I got an error telling me that the tensorflow package didn't exits in PyPI even after manually installing the latest one. Gym version is also limited by a line in run.py.

**Comment by pzhokhov** [comment]
LGTM, @tanzhenyu, any objections?

**Comment by tanzhenyu** [comment]
> LGTM, @tanzhenyu, any objections?

No objection. probably install tensorflow == 2.0.0-rc0 as latest version?

**Comment by pisiiki** [comment]
I have checked master's branch setup.py and updated acordingly. CPU/GPU and nightly versions were already correctly handled there.

**Pull request merged**
