### PR TITLE
Publish benchmark results

### PR DESCRIPTION
**Pull request by pzhokhov**
Publish results of benchmarks of public algos on Atari10M and Mujoco1M

### CODE REVIEW

**Comment by joschu** [comment]
👍

**Comment by cpacker** [comment]
@pzhokhov does "avg. 6 seeds" (from the html results page) mean seeds 0-5, or 6 (pseudo)random random seeds?

**Comment by pzhokhov** [comment]
Hi @cpacker! Avg. 6 seeds means 6 pseudorandom seeds (or, rather, 6 runs with seed None). As for plot_util.py - we are in the process of organizing and documenting the learning curve loading and visualization code; in some form the code used to generate the HTML will be published.

**Comment by cpacker** [comment]
Thanks @pzhokhov, looking forward to seeing the visualization code.

**Pull request merged**
