### PR TITLE
fix DQN learning bug

### PR DESCRIPTION
**Pull request by pzhokhov**
the problem was input was scaled twice - once by the ScaledFloatFrame Wrapper, once by the neural net code.

### CODE REVIEW

**Comment by wookayin** [comment]
How about explicitly stating as `scale=False`? I don't think the default argument value of `wrap_deepmind()` will change anytime soon, but it is more explicit and clear as rescaling is done by the DQN's nerual network code.

**Comment by pzhokhov** [comment]
@christopherhesse the second scaling was happening in the input of cnn (baselines/common/models.py:conv_only)
@wookayin Good point, however, I'd rather eventually get rid of the split logic in run.py (where different set of wrappers is built for different algorithms

**Comment by christopherhesse** [comment]
Ah, thanks.  I also saw some scaling here: https://github.com/openai/baselines/blob/4e2a888273f14c437fe6e036904e91c122ff9643/baselines/deepq/utils.py#L43 but this function doesn't appear to be used anywhere.

**Comment by pzhokhov** [comment]
yes; in fact, let me delete it

**Comment by pzhokhov** [comment]
yes, good point, thanks!

**Pull request merged**
