### PR TITLE
minor fixes from internal

### PR DESCRIPTION
**Pull request by pzhokhov**

### CODE REVIEW

**Comment by pzhokhov** [comment]
good question. I guess the right way of doing it would be create a respective gym issue... @joschu could you create a github issue about that please?

**Comment by joschu** [comment]
actually this is an issue with the rcall image or games installation -- currently we install an old version of gym

**Comment by joschu** [comment]
the issue is already fixed in gym

**Comment by christopherhesse** [comment]
Should we update gym in games @pzhokhov?

**Pull request merged**
